name: ðŸš€ Publish Website to MAIN Server

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Dev via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 21
          timeout: 900000
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/*.zip
            .env.example
            .gitignore
            composer.json
            composer.lock
            package.json
            package-lock.json
            phpunit.xml
            README.md
